version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        name: cursor-paginator
      - image: circleci/postgres:11.2
        name: db
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    working_directory: ~/cursor-paginator
    steps:
      - checkout
      - run:
          name: install dependencies build go packages (compile)
          command: go build
      - run:
          name: Run test
          command: |
            go test -v -covermode=count -coverprofile=c.out
workflows:
  version: 2
  test:
    jobs:
      - test
