version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        name: cursor-paginator
      - image: circleci/postgres:11.2
        name: db
        environment:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    working_directory: ~/cursor-paginator
    steps:
      - checkout
      - run:
          name: install dependencies build go packages (compile)
          command: go build
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run test
          command: |
            go test -v -covermode=count -coverprofile=c.out
workflows:
  version: 2
  test:
    jobs:
      - test
