version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.12
        name: cursor-paginator
    working_directory: ~/cursor-paginator
    steps:
      - checkout
      - run:
          name: install dependencies build go packages (compile)
          command: go build
      - setup_remote_docker
      - run:
          name: docker and database
          command: docker-compose up -d
      - run:
          name: Run test
          command: |
            go test -v -covermode=count -coverprofile=c.out
workflows:
  version: 2
  test:
    jobs:
      - test
